CustomProgrammingSolutions/CPS_gatsby

- src/components/Footer/Footer.js
- src/components/Footer/Footer.module.css
- src/components/Header/Header.js
- src/components/Header/Header.module.css
- src/layouts/index.css
- src/layouts/index.js
> Fix footer

- data/SiteConfig.js
- gatsby-node.js
- package.json
- src/components/ContactSnippet/ContactSnippet.js
- src/components/ContactSnippet/ContactSnippet.module.css
- src/pages/404.js
- src/pages/about.js
- src/pages/contact.js
- src/pages/index.js
- src/templates/blog-post.js
- src/templates/tutorial-post.js
- yarn.lock
> [WIP] Add a call to action/contact form to most pages

- src/components/ContactSnippet/ContactSnippet.js
- src/layouts/index.js
- src/pages/about.js
- src/pages/contact.js
- src/pages/index.js
- src/templates/post.js
> Fix window href

- data/SiteConfig.js
- gatsby-config.js
- package.json
- yarn.lock
> Add gatsby-plugin-sitemap to generate a sitemap

- gatsby-config.js
- package.json
- src/components/Footer/Footer.js
- yarn.lock
> Add gatsby-plugin-feed to generate an RSS feed

- src/components/HelmetWrapper/HelmetWrapper.js
- src/layouts/index.js
- src/pages/404.js
- src/pages/about.js
- src/pages/blog.js
- src/pages/contact.js
- src/pages/index.js
- src/pages/tags.js
- src/pages/tutorials.js
- src/templates/person.js
- src/templates/post.js
- src/templates/tag.js
> Add meta tags to make previews on social pages look better

- src/components/Footer/Footer.js
- src/components/Footer/Footer.module.css
> Add social media icons to footer

- Vagrantfile
- gatsby-config.js
Only put posts in the RSS feed, closes #90
> [MRG] Bugfix authors in rss

- gatsby-config.js
> [MRG] Ignore posts when generating RSS feed

- gatsby-config.js
- package.json
- src/layouts/index.js
- yarn.lock
> Add LaTeX support

- src/templates/post.js
> Add post excerpt as meta description in post.js

- src/components/Footer/Footer.js
- src/components/NavBar/NavBar.js
- src/pages/services.js
> [MRG] Create services page

- src/templates/tag.js
> Fix bug where the heading of tag pages would be wrong

- src/components/ContactSnippet/ContactSnippet.js
- src/pages/blog.js
- src/templates/person.js
- src/templates/post.js
Get rid of debug log outputs. Closes #107
> [MRG] Remove console log debug output

- content/blog-posts/2018-04-01/sample-blog-post.md
- content/blog-posts/2018-04-03/second-blog-post.md
- content/people/sam.md
- content/tutorial-pages/2018-04-07/how-to-write-sample-blogs.md
- gatsby-node.js
- src/components/AuthorsInfo/AuthorsInfo.js
- src/components/PostListing/PostListing.js
- src/pages/blog.js
- src/pages/tutorials.js
- src/templates/post.js
- src/templates/tag.js
See corresponding PR (24) on content repo
> [MRG] Add support for multiple authors on posts

- content/blog-posts/2018-09-25/company-blog-post.md
> [MRG] Deal with null author issue

- src/templates/person.js
> [MRG] Add a person's mini blurb as the meta description

- src/styles/code.scss
Not sure why this does it, but it closes #106
> Fix inline code whitespace issue

- gatsby-node.js
- src/components/PostListing/PostListing.js
- src/helpers/AuthorHelpers.js
- src/pages/blog.js
- src/pages/team.js
- src/pages/tutorials.js
- src/templates/person.js
- src/templates/person.module.scss
- src/templates/post.js
- src/templates/tag.js
> [MRG] Feature posts by author and other fixes

- content/services/coming-soon.md
- content/services/sample-service.md
- gatsby-config.js
- gatsby-node.js
- src/templates/service.js
Create detail pages for services.
TODO:
> [WIP] Service detail pages

- gatsby-node.js
- src/templates/service.js
> [MRG] Fix CTA bugs in service page

- gatsby-node.js
> [MRG] Refactor: Remove unused items from graphql query

- src/pages/about.js
Seeing as we are not focusing on that now I have removed references to Internet Of Things (IoT) on the about page.
> [MRG] Remove writing about IoT services

- src/templates/person.js
This will provide a link to the main URL provided in the bio pages.
Closes #140
> [MRG] Add a URL section in the bio page

- src/templates/person.js
> [MRG] Added check for URL before rendering it

- src/templates/person.js
> [MRG] Fix link href
